In [2]:
import numpy as np

- 상수값(scalar): 10, 3.14, 'aa'
- 1차원(vector): [10,20,30]
- 2차원(matrix): [ [10,20,30],[30,40,50] ] # 2x3
- 3차원:[ [ [10,20,30],[30,40,50] ], [ [10,20,30],[30,40,50] ] ] # 2x2x3

In [3]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

In [6]:
print(type(arr))
type(arr)

<class 'numpy.ndarray'>


numpy.ndarray

In [5]:
arr1 = np.array([[11,22],[33,44]])
arr1

array([[11, 22],
       [33, 44]])

## 핵심 속성

In [11]:
arr

array([11, 22, 33, 44, 55])

In [7]:
arr.dtype

dtype('int32')

In [12]:
arr.size

5

In [13]:
arr.shape

(5,)

In [15]:
arr1.shape

(2, 2)

In [16]:
arr.ndim

1

In [17]:
arr1.ndim

2

In [18]:
arr1

array([[11, 22],
       [33, 44]])

In [20]:
arr1.T

array([[11, 33],
       [22, 44]])

##  메소드

In [21]:
## 형변환
arr = arr.astype(np.float32)
arr

array([11., 22., 33., 44., 55.], dtype=float32)

In [22]:
## reshape
arr3 = np.array([1,2,3,4,5,6])
arr3

array([1, 2, 3, 4, 5, 6])

In [23]:
arr3.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr3.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
arr3.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
arr3.reshape(-1,3,2)

array([[[1, 2],
        [3, 4],
        [5, 6]]])

## 통계관련...

In [9]:
class Test:
    def __init__(self):
        self.a=10
        self.b=20
    def show(self):
        print(self.a, self.b)

In [10]:
obj = Test()
obj.a # 속성

10