In [1]:
import numpy as np

In [2]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

## 추가

In [3]:
np.append(arr, [100, 200])

array([ 11,  22,  33,  44,  55, 100, 200])

In [4]:
arr

array([11, 22, 33, 44, 55])

In [7]:
arr = np.append(arr, [100, 200]) # 추가된 것 실제 적용
arr

array([ 11,  22,  33,  44,  55, 100, 200, 100, 200, 100, 200])

In [8]:
np.insert(arr, 1, [1,2])

array([ 11,   1,   2,  22,  33,  44,  55, 100, 200, 100, 200, 100, 200])

In [9]:
arr

array([ 11,  22,  33,  44,  55, 100, 200, 100, 200, 100, 200])

In [10]:
arr = np.insert(arr, 1, [1,2])
arr

array([ 11,   1,   2,  22,  33,  44,  55, 100, 200, 100, 200, 100, 200])

## 수정

In [12]:
arr[0] = 100
arr

array([100,   1,   2,  22,  33,  44,  55, 100, 200, 100, 200, 100, 200])

In [14]:
arr[1:3] = 2
arr

array([100,   2,   2,  22,  33,  44,  55, 100, 200, 100, 200, 100, 200])

In [15]:
arr[1:3] = [5,6]

In [16]:
arr

array([100,   5,   6,  22,  33,  44,  55, 100, 200, 100, 200, 100, 200])

## 삭제

In [17]:
np.delete(arr, [0,2])

array([  5,  22,  33,  44,  55, 100, 200, 100, 200, 100, 200])

In [18]:
arr

array([100,   5,   6,  22,  33,  44,  55, 100, 200, 100, 200, 100, 200])

In [20]:
arr = np.delete(arr, [0,2])
arr

array([ 22,  44,  55, 100, 200, 100, 200, 100, 200])

In [21]:
np.where(arr<30)

(array([0], dtype=int64),)

In [24]:
# 2분 퀴즈
## 40 이상인 값을 삭제하십시오.
# np.delete(arr, arr>=40) #1.19버전 이상만 지원
np.delete(arr, np.where(arr >= 40))

array([22])

In [25]:
arr

array([ 22,  44,  55, 100, 200, 100, 200, 100, 200])

In [26]:
np.where(arr<30, 'B', 'A')

array(['B', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'], dtype='<U1')

## 다중조건

In [27]:
np. select([arr>40, arr>30, arr>0], ['A', 'B', 'C'])

array(['C', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A'], dtype='<U3')

## 정렬

In [28]:
arr[0] = 100

In [29]:
np.sort(arr)

array([ 44,  55, 100, 100, 100, 100, 200, 200, 200])

In [30]:
arr

array([100,  44,  55, 100, 200, 100, 200, 100, 200])

In [33]:
arr = np.sort(arr)
arr

array([ 44,  55, 100, 100, 100, 100, 200, 200, 200])

### 연습문제

In [34]:
kor = np.array([60,55,70,30,20,90])
kor

array([60, 55, 70, 30, 20, 90])

7분 퀴즈..
1. 국어점수가 80점 이상인 값을 구하시오.
2. 국어점수가 50점 이상 80이하인 값을 구하시오.
3. 국어점수 top5를 구하시오.

In [52]:
# 1. 국어점수가 80점 이상인 값을 구하시오.
kor[kor>=80]

array([90])

In [53]:
# 국어점수가 50점 이상 80이하인 값을 구하시오.
kor[(kor>=50) & (kor<=80)]

array([60, 55, 70])

In [55]:
# 국어점수 top5를 구하시오.
np.sort(kor)[-1:-6:-1]

array([90, 70, 60, 55, 30])

#### 7분 퀴즈..
#### 4.국어점수가 40점이하인 데이터를 삭제하십시오.
#### 5.국어점수가 50점 이상인 데이터에 가산점 10%를 부여하시오.
#### 6.국어점수가 70점 이상이면 '합격' 아니면 '불합격'으로 구하시오.

In [59]:
# 4.국어점수가 40점이하인 데이터를 삭제하십시오.
np.delete(kor, np.where(kor<=40))

array([60, 55, 70, 90])

In [63]:
# 5.국어점수가 50점 이상인 데이터에 가산점 10%를 부여하시오.
np.where(kor>=50, kor*1.1, kor)

array([66. , 60.5, 77. , 30. , 20. , 99. ])

In [62]:
# 6.국어점수가 70점 이상이면 '합격' 아니면 '불합격'으로 구하시오.
np.where(kor>=70,'합격','불합격')

array(['불합격', '불합격', '합격', '불합격', '불합격', '합격'], dtype='<U3')