In [1]:
import numpy as np

In [2]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

## np의 함수, ndarray객체의 멤버함수

In [3]:
arr.sum()

165

In [4]:
np.sum(arr)

165

In [5]:
arr.mean()

33.0

In [6]:
np.mean(arr)

33.0

In [7]:
arr.max() # np.max(arr)

55

In [8]:
arr.argmax() # 인덱스 최대값

4

In [9]:
arr

array([11, 22, 33, 44, 55])

In [11]:
arr.min() # np.min(arr)

11

In [12]:
arr.argmin()

0

In [14]:
arr.std()

15.556349186104045

In [15]:
np.median(arr)

33.0

In [16]:
np.quantile(arr, q=0.5)

33.0

In [17]:
np.quantile(arr, q=[0.25, 0.5, 0.75])

array([22., 33., 44.])

In [19]:
np.percentile(arr, q=[25,50,75])

array([22., 33., 44.])

In [13]:
arr

array([11, 22, 33, 44, 55])