In [1]:
import numpy as np

In [2]:
data = np.array([[1,2,3], [7,5,2],[10,1,8],[6,3,4]])
data                

array([[ 1,  2,  3],
       [ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

## 2차원 인덱싱, 슬라이싱
- [행, 열]
- 3차원: [면, 행, 열]

In [4]:
data.shape

(4, 3)

In [5]:
data[0]

array([1, 2, 3])

In [6]:
data[1]

array([7, 5, 2])

In [7]:
data[-1]

array([6, 3, 4])

In [8]:
data[0,0]

1

In [11]:
data[2,2]

8

In [12]:
data[[0,2]]

array([[ 1,  2,  3],
       [10,  1,  8]])

In [13]:
data[1:3]

array([[ 7,  5,  2],
       [10,  1,  8]])

In [14]:
data[1:]

array([[ 7,  5,  2],
       [10,  1,  8],
       [ 6,  3,  4]])

In [15]:
data[1:, 1:]

array([[5, 2],
       [1, 8],
       [3, 4]])

In [16]:
data[1:3, ::2] # [row , colum]

array([[ 7,  2],
       [10,  8]])

### 마지막 컬럼을 제외하고 데이터를 선택하시오.

In [19]:
data[:, :-1] # 0<= c < -1

array([[ 1,  2],
       [ 7,  5],
       [10,  1],
       [ 6,  3]])

In [20]:
### 마지막 컬럼을 선택하시오.
data[: , -1]

array([3, 2, 8, 4])

In [21]:
data[:,[-1]]

array([[3],
       [2],
       [8],
       [4]])

## 2차원 boolean indexing(행단위)

In [23]:
data[[True, False, False, True]]

array([[1, 2, 3],
       [6, 3, 4]])

## 2차원 연산

In [24]:
data + 2

array([[ 3,  4,  5],
       [ 9,  7,  4],
       [12,  3, 10],
       [ 8,  5,  6]])

In [25]:
data *2

array([[ 2,  4,  6],
       [14, 10,  4],
       [20,  2, 16],
       [12,  6,  8]])

In [26]:
data + [1,2,3]

array([[ 2,  4,  6],
       [ 8,  7,  5],
       [11,  3, 11],
       [ 7,  5,  7]])

In [29]:
data[1] + 2

array([9, 7, 4])

In [30]:
data[1] = data[1] + 2

In [31]:
data

array([[ 1,  2,  3],
       [ 9,  7,  4],
       [10,  1,  8],
       [ 6,  3,  4]])

In [33]:
data[:, 0] > 5

array([False,  True,  True,  True])

In [34]:
data [data[:, 0] > 5] # data([False,  True,  True,  True])

array([[ 9,  7,  4],
       [10,  1,  8],
       [ 6,  3,  4]])

## 2차원 추가, 수정, 삭제, 검색, 정렬

In [35]:
ax = np.array([[1,2], [3,4]])
ay = np.array([[5,6], [7,8]])

## 추가

In [36]:
np.append(ax, ay) # 1차원으로 추가

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
np.append(ax, ay, axis=0) #  행으로 추가

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [38]:
np.append(ax, ay, axis=1) #  컬럼으로 추가

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [39]:
np.hstack((ax,ay)) 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [40]:
np.vstack((ax,ay))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## 삭제

In [42]:
np.delete(data, [0,2], axis=0)

array([[9, 7, 4],
       [6, 3, 4]])

In [43]:
np.delete(data, [0,2], axis=1)

array([[2],
       [7],
       [1],
       [3]])

## 정렬

In [48]:
np.sort(data) # axis=-1

array([[ 1,  2,  3],
       [ 4,  7,  9],
       [ 1,  8, 10],
       [ 3,  4,  6]])

In [51]:
np.sort(data, axis=None)

array([ 1,  1,  2,  3,  3,  4,  4,  6,  7,  8,  9, 10])

In [50]:
np.sort(data, axis=0)

array([[ 1,  1,  3],
       [ 6,  2,  4],
       [ 9,  3,  4],
       [10,  7,  8]])

In [52]:
np.sort(data, axis=1)

array([[ 1,  2,  3],
       [ 4,  7,  9],
       [ 1,  8, 10],
       [ 3,  4,  6]])

## 2차원 통계
- 디폴트 axis = None 1차원의 통계
- axis = 0 컬럼별 통계
- axis = 1 행별 통계

In [53]:
data.sum()

58

In [56]:
data.sum(axis=0)

array([26, 13, 19])

In [57]:
data.sum(axis=1)

array([ 6, 20, 19, 13])

In [64]:
data.mean() # data.mean(axis=1)

4.833333333333333

In [63]:
data.mean(axis=0)

array([6.5 , 3.25, 4.75])

In [62]:
data.mean(axis=1)

array([2.        , 6.66666667, 6.33333333, 4.33333333])

In [67]:
data.max()

10

In [68]:
data.max(axis=0)

array([10,  7,  8])

In [69]:
data.max(axis=1)

array([ 3,  9, 10,  6])

In [65]:
data.argmax()

6

In [71]:
data.argmax(axis=0)

array([2, 1, 2], dtype=int64)

In [72]:
data.argmax(axis=1)

array([2, 0, 0, 0], dtype=int64)

In [73]:
for n in data:
    print(n)

[1 2 3]
[9 7 4]
[10  1  8]
[6 3 4]


In [70]:
data

array([[ 1,  2,  3],
       [ 9,  7,  4],
       [10,  1,  8],
       [ 6,  3,  4]])